[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.mypy]
ignore_missing_imports = true

[tool.pylint]
disable = "all"
enable = "simplifiable-if-statement, simplifiable-if-expression, unnecessary-pass, used-before-assignment, superfluous-parens, unnecessary-dunder-call"

[tool.ruff]
line-length = 100
builtins = ["__version__"]

[tool.ruff.lint]
select = [
    "A", "AIR", "ASYNC",
    "B",
    "C", "C4", "COM", "CPY",
    "DJ", "DOC", 
    "E", "ERA", "EXE",
    "F", "FA", "FAST", "FLY",
    "G",
    "I", "ICN", "INT", "INP", "ISC",
    "LOG",
    "N", "NPY",
    "PIE", "PGH", "PLR", "PYI",
    "Q",
    "RET", "RSE", "RUF100",
    "SIM", "SLOT",
    "T10", "TCH",
    "UP",
    "W",
    "YTT"
]
ignore = ["E402", "E501"]
# D, ANN, S, BLE, FBT, DTZ, EM, T20, PT, SLF, TID, ARG, PTH, TD, FIX, PD, PLC, PLE, PLW, TRY, PERF,
# FURB, other RUF

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"test*" = ["PLR0913", "PLR2004"]

[tool.isort]
profile = "black"
