[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.mypy]
ignore_missing_imports = true

[tool.pylint]
disable = "all"
enable = "simplifiable-if-statement, simplifiable-if-expression, unnecessary-pass, used-before-assignment, superfluous-parens, unnecessary-dunder-call"

[tool.ruff]
line-length = 100
builtins = ["__version__"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN", "ARG",
    "BLE",
    "D", "DTZ",
    "E402", "E501", "EM",
    "FBT", "FIX", "FURB",
    "PD", "PERF", "PLC", "PLE", "PLW", "PT", "PTH",
    "RUF012", "RUF015",
    "S", "SLF",
    "T20", "TD", "TID", "TRY",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"test*" = ["PLR0913", "PLR2004"]

[tool.isort]
profile = "black"
