[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.mypy]
ignore_missing_imports = true

[tool.pylint]
disable = "all"
enable = "simplifiable-if-statement, simplifiable-if-expression, unnecessary-pass, used-before-assignment, superfluous-parens, unnecessary-dunder-call"

[tool.pytest.ini_options]
addopts = "--cov=floodmodeller_api --cov-fail-under=79"

[tool.ruff]
line-length = 100
builtins = ["__version__"]

[tool.ruff.lint]
select = ["A", "ASYNC", "B", "C", "COM", "DJ", "E", "ERA", "EXE", "F", "FLY", "G", "I", "ISC", "N", "PLR", "RET", "RUF100", "SIM", "T10", "TRY200", "UP", "W", "YTT"]
ignore = ["E402", "E501"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"test*" = ["PLR0913", "PLR2004"]
