[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
ignore_missing_imports = true

[tool.pylint]
disable = "all"
enable = "dangerous-default-value, unneeded-not, no-else-return, no-else-continue, simplifiable-if-statement, simplifiable-if-expression, unnecessary-comprehension, consider-using-in, redefined-builtin, unused-variable, unnecessary-pass, used-before-assignment, superfluous-parens, unnecessary-dunder-call, no-else-raise, consider-iterating-dictionary, raise-missing-from"

[tool.pytest.ini_options]
addopts = "--cov=floodmodeller_api --cov-fail-under=78"

[tool.ruff]
line-length = 100
builtins = ["__version__"]

[tool.ruff.lint]
select = ["F", "E", "W", "C", "I", "N", "RUF100"]
ignore = ["E402", "E501"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
