name: Lint

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  

      - name: Python Linter
        uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-isort: false
          extra-black-options: "--line-length 100"
          extra-mypy-options: "--ignore-missing-imports"