name: Docs
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"

    steps:
      - uses: actions/checkout@v2  

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          activate-environment: true      
      
      - name: Install reqs
        run: |          
          uv pip install .
          uv pip install -r requirements.txt

      - name: Create documentation
        run: sphinx-build -b html docs/source docs/build/html -W 
