name: Lint

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  

      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "src"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          pylint-options: "--rcfile=setup.cfg"
          isort-options: "-w 100"
          black-options: "--check --line-length 100"