name: Build

on:
  push:
    branches: [ main ]
    paths: [ "floodmodeller_api/version.py" ]

env:
  PYTHON_VERSION: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.extract_version.outputs.package_version }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build twine

    - name: Extract version
      id: extract_version
      run: |
        set -eo pipefail
        PACKAGE_VERSION=$(python -c 'from floodmodeller_api.version import __version__; print(__version__)')
        echo "::set-output name=package_version::$PACKAGE_VERSION"

    - name: Build the package
      run: python -m build

    - name: Publish the package to TestPyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload --repository testpypi dist/*

  install:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install the package from TestPyPI
      run: >
        pip install
        -i https://test.pypi.org/simple/
        --extra-index-url https://pypi.org/simple
        "floodmodeller-api==${{ needs.build.outputs.package_version }}"

    - name: Run tests
      run: pytest --pyargs floodmodeller_api
