name: Lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"
      FILES_TO_CHECK: floodmodeller_api sample_code scripts setup.py
      LINE_LENGTH: "100"

    steps:
      - uses: actions/checkout@v2  

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run isort
        run: >
          isort
          ${{ env.FILES_TO_CHECK }}
          --profile black
          --line-length ${{ env.LINE_LENGTH }}
          --check-only
          --diff

      - name: Run black
        run: >
          black
          ${{ env.FILES_TO_CHECK }}
          --check
          --line-length ${{ env.LINE_LENGTH }}

      - name: Run flake8
        run: >
          flake8
          ${{ env.FILES_TO_CHECK }}
          --ignore E203,E402,E501,W503
          --per-file-ignores __init__.py:F401
          --builtins __version__
          --max-complexity 10

      - name: Run mypy
        run: >
          mypy
          ${{ env.FILES_TO_CHECK }}
          --ignore-missing-imports

      - name: Run pylint
        run: >
          pylint
          ${{ env.FILES_TO_CHECK }}
          --disable=all
          --enable=
          dangerous-default-value,
          unneeded-not,
          no-else-return,
          no-else-continue