name: Lint

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  

      - name: Python Linter
        uses: ricardochaves/python-lint@v1.4.0
        with:
          use-black: true
          use-mypy: true
          extra-black-options: "--check --line-length 100"
          extra-mypy-options: "--ignore-missing-imports"