name: Docs

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"

    steps:
      - uses: actions/checkout@v2  

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create documentation
        run: |
          cd docs
          make html
