name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.9", "3.10", "3.11", "3.12"]
        OS: [windows-latest, ubuntu-latest]
  
    runs-on: ${{ matrix.OS }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          cache: pip
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Run unit tests with coverage (Windows)
        if: matrix.OS == 'windows-latest'
        run: pytest . -v --cov=floodmodeller_api --cov-fail-under=83
    
      - name: Run unit tests without coverage (Ubuntu)
        if: matrix.OS == 'ubuntu-latest'
        run: |
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:floodmodeller_api/libs"
          pytest . -v