name: Unit Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
  
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Run unit tests with coverage
        if: matrix.os == 'windows-latest'
        run: pytest . -v --cov=floodmodeller_api --cov-fail-under=79
    
      - name: Run unit tests without coverage
        if: matrix.os == 'ubuntu-latest'
        run: |
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:floodmodeller_api/libs"
          pytest . -v